import Head from 'next/head'
import Image from 'next/image'
import { Cormorant  as Font } from 'next/font/google'

const font = Font({ weight: '400', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Generative Choose Your Own Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className='header'>
          <h1 className='book-title'>The Generative Enigma: A Castle of Creative Conundrums</h1>
        </header>
        <article className='chapter'>
          <header>
            <h2 className='chapter-number'>Chapter 1</h2>       
            <h3 className='chapter-title'>The Rain</h3>       
          </header>
    <p>
  You can&apos;t help but eavesdrop on the conversations around you as the train rolls towards the platform. Everyone seems to be talking about one thing. The storm of the century. &quot;It&apos;s supposed to be a real gullywasher&quot; says the man sitting behind you. &quot;No way it will be worse than that frog-strangler we had in &apos;59&quot;, &quot;they had to evacuate the whole town!&quot; &quot;They said it&apos;ll be the worst storm in 1000 years&quot; &quot;How do they know how bad the storms were a thousand years ago?&quot; &quot;I don&apos;t know how they know I just know they know&quot;. &quot;I heard it&apos;s going to be the worst storm in years,&quot; you hear a woman say a few rows up. You shift uncomfortably in your seat. Wondering if you&apos;re really prepared for what&apos;s to come.
    </p>
<p>
  As you step off the train into the drizzling rain, you feel a sense of anticipation. There&apos;s something thrilling about being out in the midst of a storm. You just hope you make it to your aunt&apos;s before it gets too bad. You set out house, determined to brave whatever the weather has in store. The streets are nearly empty, with only a few other brave souls venturing out into the deluge. You check your pocketwatch and move it to the inside of your jacket to protect it from the rain. It&apos;s 2:12. You should be able to make it within 20 minutes if you don&apos;t get lost. 
</p> 
<p> You begin to navigate the town&apos;s streets, making your way toward your Aunt&apos;s house. At every turn, the rain appears to gain confidence, transforming from an innocent drizzle into a persistent shower. &quot;Well, this is just perfect,&quot; you muse, trying to shield yourself from the increasingly aggressive raindrops with one hand while clutching your luggage with the other.
</p>
<p>
  As the rain intensifies, you try to recall if there was a more direct route to your aunt&apos;s house. The soggy map in your pocket is now about as helpful as a chocolate teapot. &quot;If only I had listened to my mom when she insisted on teaching me the town&apos;s shortcuts,&quot; you lament, shaking your head at your own stubbornness. The rain is coming down harder now, and the wind is making it difficult to see.
</p>
<p>
  A flickering light in a nearby window catches your eye. The warm, golden glow emanates from an old, dusty bookshop that appears to defy the storm outside, its windows adorned with a curious array of books, trinkets, and an owl perched on a stack of tomes.
</p>
<p>
Seeking refuge from the weather, you push open the door, a bell chiming softly overhead. The musty scent of old paper, leather, and something else (maybe cinnamon?) fills your nostrils as you step inside. Your eyes linger on the owl, its head tilting curiously as it watches you.
    </p>
<p>
&quot;You must be here for the storm,&quot; an elderly woman speaks from behind a counter, her voice warm and welcoming. You start to open your jacket to shake off the water you&apos;ve collected since the station. She glances at the pocket watch hanging from your inside pocket coat. &quot;That&apos;s a beautiful timepiece you have there,&quot; she comments, her eyes twinkling with interest.
    </p>
    <p>&quot;Thanks, it was my great-grandfathers.&quot; you say, &quot;I&apos;m here to visit my aunt, she lives in his old house up on Sea Rd.&quot;</p>
<p>
    Her eyes twinkle with the promise of adventure and intrigue. &quot;It&apos;s a good thing you came in. You&apos;ll catch your death out there in this dreadful weather! Now give me that coat and I&apos;ll hang it by the fire to dry&quot;
</p>
<p>
She disappears for a moment into the shadowy depths of the store, only to return with two books in her hands.
</p>
<p>
  &quot;Here,&quot; she says, offering you the books. &quot;Choose wisely, for each holds a different tale.&quot;
</p>
<p>
As you hold the books, you notice that their covers seem to shift and change, as though telling a story of their own. The first book&apos;s cover shows a storm-tossed sea with a ship struggling against the waves, while the second book features a sunlit path leading into an enchanted forest. The decision is yours, and with it, the story that will unfold.
</p>


If you choose the first book, with the storm-tossed sea, turn to page 6.

If you choose the second book, with the sunlit path, turn to page 12.

        </article>
        <article className='chapter'>
          <header>
            <h2 className='chapter-number'>Chapter 2</h2>       
            <h3 className='chapter-title'>The Enchanted Entrance</h3>       
          </header>

    <p>
A dense fog enveloped the lonely road, as if to obscure the path of any curious traveler. The air hung heavy with an unseen weight, a palpable presence that tingled at the back of the neck, sending shivers down the spine. The silhouette of the castle loomed in the distance, its dark, brooding visage somehow alluring and foreboding simultaneously. Despite the tales and whispered warnings that shrouded this mysterious structure in fear, the intrepid adventurer could not resist the magnetic pull of the unknown.
    </p>
<p>
Upon reaching the castle&apos;s entrance, the traveler noticed the stone walls adorned with intricate carvings, depicting scenes that seemed to dance and shimmer in the dim light of the setting sun. The iron gate groaned in protest as it swung open, revealing a grand foyer bathed in an ethereal glow. The air here was thick with age, the taste of a long-lost past lingering on every breath.
</p>
    <p>
As the traveler ventured deeper into the castle, they were struck by the overwhelming sense of forgotten stories and hidden knowledge waiting to be discovered. The atmosphere of the castle seemed to hum with a creative energy, beckoning the visitor to unlock its secrets.
</p>
    <p>
Before long, the traveler found themselves standing before a massive door, its surface etched with curious patterns and symbols. The designs seemed to writhe and contort before their very eyes, yet somehow, they could discern a single word: &quot;Color.&quot; Instinctively, they reached out to touch the word, and as their fingers made contact, the symbols began to glow, illuminating the room with vibrant hues.
</p>
    <p>
A voice echoed through the chamber, deep and resonant, yet strangely soothing. &quot;To proceed, you must create a work of generative art using the element of color. Choose wisely, for your choice will determine your path through these ancient walls.&quot;
    </p>

Three options lay before the traveler:

Create a vibrant mosaic, harnessing the full spectrum of colors to bring life to an otherwise dull castle room. (Pages 6-9)
Paint a dull landscape, using muted tones and somber shades to reflect the oppressive atmosphere of the castle. (Pages 10-12)
Assemble a monochrome portrait, capturing the essence of the forgotten souls that once dwelled within these walls. (Pages 13-15)
As the traveler pondered their choice, they could not shake the feeling that unseen eyes were watching them, waiting to witness the first step of their journey into the heart of the castle. The weight of the decision bore down on them, and with a deep breath, they made their choice, setting in motion a chain of events that would lead them through the labyrinthine corridors of the castle, each choice forging the path to their ultimate fate.

In the world of the Generative Enigma, the line between reality and imagination was blurred, and the traveler was about to embark on a journey that would challenge their creativity and reshape their understanding of the world. As the haunting melodies of the castle whispered their secrets, the traveler prepared to face the unknown, guided by the creative force that dwelled within these ancient walls.
        </article>
      </main>
    </>
  )
}
